services:
  - type: web
    name: thm-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_APP
        value: api/app.py
      - key: FLASK_ENV
        value: production
      - key: USE_MOCK_DATA
        value: "True"
    healthCheckPath: / 